export const languages = [
  { value: 'English', label: 'English' },
  { value: 'Spanish', label: 'Spanish' },
  { value: 'French', label: 'French' },
  { value: 'German', label: 'German' },
  { value: 'Italian', label: 'Italian' },
  { value: 'Chinese', label: 'Chinese' },
  { value: 'Japanese', label: 'Japanese' },
  { value: 'Korean', label: 'Korean' },
  { value: 'Hindi', label: 'Hindi' },
  { value: 'Arabic', label: 'Arabic' },
]
export const models = [
  { value: 'gemini-1.5-pro-latest', label: 'Gemini 1.5 Pro' },
  { value: 'gemini-1.5-flash', label: 'Gemini 1.5 flash' },
]
export const chatSuggestions = [
  'What was my overall mood last week, and how did it change day by day?',
  'Can you show me the most common emotion I experienced over the past month?',
  'What was my sentiment score trend over the last 7 days? Did it go up or down?',
  'Which journal entry had the highest sentiment score in the last two weeks, and why?',
  'Have I written more about positive or negative experiences recently?',
  'Can you find a pattern in the subjects I’ve been journaling about over the last month?',
  'Did I use any specific language (like French) consistently last week in my entries?',
  'What colors have been most associated with my entries this past week, and what do they signify?',
  'Can you compare my average sentiment score last week to this week so far?',
  'Were there any days last week where my mood completely contrasted with the rest of the week?',
]
export const moodTags = [
  // Positive Moods
  'Happy',
  'Excited',
  'Calm',
  'Grateful',
  'Confident',
  'Optimistic',
  'Relaxed',
  'Cheerful',
  'Proud',
  'Inspired',
  // Neutral Moods
  'Neutral',
  'Content',
  'Reflective',
  'Tired',
  'Indifferent',
  'Focused',
  'Thoughtful',
  'Curious',
  'Quiet',
  'Balanced',
  // Negative Moods
  'Sad',
  'Anxious',
  'Stressed',
  'Angry',
  'Frustrated',
  'Lonely',
  'Disappointed',
  'Overwhelmed',
  'Guilty',
  'Fearful',
  // Complex or Mixed Moods
  'Nostalgic',
  'Hopeful',
  'Bittersweet',
  'Confused',
  'Restless',
  'Determined',
  'Regretful',
  'Vulnerable',
  'Hesitant',
  'Empowered',
] as const
export const reviews = [
  {
    name: 'Abebe',
    username: '@abebe',
    body: 'The Mood AI Journal has completely transformed how I reflect on my day. The emotional insights are spot on!',
    img: 'https://images.unsplash.com/photo-1731497772419-235b4fb71a99',
  },
  {
    name: 'Bontu',
    username: '@bontu',
    body: "Kun yeroo jalqabaati. Yaada koo hubachuu danda'uu nan dinqisiifadha!",
    img: 'https://images.unsplash.com/photo-1732923323323-8d2e805661df',
  },
  {
    name: 'Lensa',
    username: '@lensa',
    body: 'Mood AI Journal gorsa tokkoon tokkoo itti kennamee nama gammachiisa. Qaama jireenya koo godheera.',
    img: 'https://images.unsplash.com/photo-1601317106123-d6c7b7f8e1a7',
  },
  {
    name: 'Aster',
    username: '@aster',
    body: "I love how this journal understands me better than I understand myself. It's my go-to reflection tool.",
    img: 'https://images.unsplash.com/photo-1529655683826-aba9b3e77383',
  },
  {
    name: 'Kebede',
    username: '@kebede',
    body: 'The emotional analysis and recommendations have been a game-changer. Journaling feels so meaningful now.',
    img: 'https://images.unsplash.com/photo-1731505183738-4987ea65caa5',
  },
  {
    name: 'Tsehay',
    username: '@tsehay',
    body: "The way it captures my mood and provides actionable advice is incredible. It's like journaling with a guide.",
    img: 'https://images.unsplash.com/photo-1517849845537-4d257902454a',
  },
  {
    name: 'Fikadu',
    username: '@fikadu',
    body: 'Writing in this journal feels like having a personal coach for emotional growth. Highly recommend it!',
    img: 'https://images.unsplash.com/photo-1553729459-efe14ef6055d',
  },
  {
    name: 'Hirut',
    username: '@hirut',
    body: "I've tried many journals, but none come close to the Mood AI Journal. It's intuitive and deeply insightful.",
    img: 'https://images.unsplash.com/photo-1721332149274-586f2604884d',
  },
  {
    name: 'Debela',
    username: '@debela',
    body: 'Barreeffama koo yeroo hunda iftoomina sammuu naaf kenna. Guddina kootif hedduu na fayyada.',
    img: 'https://images.unsplash.com/photo-1734312621516-3d258db95e76',
  },
  {
    name: 'Ayantu',
    username: '@ayantu',
    body: "Bu'uura haala koo hubachuun rakkoo koo furuu danda'e. Namatti tola!",
    img: 'https://images.unsplash.com/photo-1734613876170-079f67aa0d15',
  },
]
